export {default as dataSlice} from './reviewsSilce'
export {default as cartSlice} from './cartSlice'
export {default as policySlice} from './policySlice'
export {default as attributesSlice} from './attributesSlice'
export {default as productsSlice} from './productsSlice'
export {default as bannerSlice} from './bannerSlice'
export {default as categoriesSlice} from './categoriesSlice'
export {default as reviewsSilce} from './reviewsSilce'